<a href="https://colab.research.google.com/github/acubillosde/UNAL-Herramientas-Visualizacion/blob/main/03-Tablas_Contingencia.ipynb#scrollTo=1quZ2aUgC9GO" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Recuerda que una vez abierto, Da clic en "Copiar en Drive", de lo contrario no podras almancenar tu progreso**

Nota: no olvide ir ejecutando las celdas de código de arriba hacia abajo para que no tenga errores de importación de librerías o por falta de definición de variables.

In [2]:
!wget --no-cache -O init.py -q https://raw.githubusercontent.com/acubillosde/UNAL-Herramientas-Visualizacion/main/init.py
import init; init.init(force_download=False);

# **Tablas de Contingencia**

Una tabla de contigencia es una herramienta utilizada en estadística, la cual consiste en crear al menos dos filas y dos columnas para representar datos categóricos en términos de conteos de frecuencia.

El objetivo de una tabla de contingencia es representar en un resumen, la relación entre diferentes variables categóricas.

Definimos una tabla de contingencia de la siguiente manera

$$
    \begin{equation}
\begin{bmatrix}
f_{11} & f_{12} & \cdots & f_{1j} & \cdots & f_{1r}\\
f_{21} & f_{22} & \cdots & f_{2j} & \cdots & f_{2r}\\
\vdots & \vdots & \ddots & \vdots & \ddots & \vdots\\
f_{i1} & f_{i2} & \cdots & f_{ij} & \cdots & f_{ir}\\
\vdots & \vdots & \ddots & \vdots & \ddots & \vdots\\
f_{c1} & f_{c2} & \cdots & f_{cj} & \cdots & f_{cr}
\end{bmatrix}
\end{equation}
$$


La frecuencia de la fila $i$ fila y la columna $j$ se denota por $f_{ij}$.

Si sumamos todas las frecuencias conjuntas obtenemos el tamaño de la muestra:

$$
    \sum_{i=1}^c\sum_{j=1}^rf_{ij} = n
$$

### **Objetivos de una tabla de contingencia**

La tabla permite medir la interacción entre dos variables para conocer una serie de información “oculta”  de gran utilidad para comprender con mayor claridad los resultados de una investigación. 

La tabla sólo mostrará los encuestados que respondieron ambas preguntas, lo que significa que las frecuencias mostradas pueden diferir de una tabla de frecuencias estándar.

El informe que ofrece también mostrará las Estadísticas Chi-cuadrado de Pearson, el cual representa el grado de correlación entre las variables que usan el chi-cuadrado, el valor p y el grado de libertad.

Los objetivos de la tabla de contingencia son los siguientes: 

* Ordenar la información recolectada para un estudio cuando los datos se encuentran divididos de forma bidimensional, esto significa a que se relaciona con dos factores cualitativos.   

* El otro objetivo de la tabla de contingencia es analizar si hay una relación entre las variables cualitativas, ya sean dependientes o independientes. 

### **Ventajas de realizar una tabla de contingencia**

Entre los principales beneficios de realizar una tabla de contingencia se encuentran los siguientes: 

1. Facilita la lectura de los datos recolectados, ya que permite agruparlos cuando aún se encuentran sin procesar, lo que disminuye el margen de error al realizar un informe de investigación.

2. Gracias a la tabla de contingencia es posible realizar gráficas que permitan visualizar la información fácilmente para su comprensión. 

3. A diferencia de otros métodos estadísticos de análisis de datos, la tabla de contingencia permite ahorrar tiempo durante la correlación de variables.  

4. Las tablas ofrecen resultados claros y precisos que permiten tomar mejores decisiones y crear estrategias basadas en datos.

### **Ejemplo**
Apliquemos lo anterior a la siguiente base datos

Primero importemos las librerias necesarias

In [1]:
import pandas as pd

Carguemos la base de datos

In [55]:
banco = pd.read_csv('local/data/german_credit_data.csv')
print(banco.shape)
banco.head()

(1000, 11)

,Unnamed: 0,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk
0,0,67,male,2,own,NaN,little,1169,6,radio/TV,good
1,1,22,female,2,own,little,moderate,5951,48,radio/TV,bad
2,2,49,male,1,own,little,NaN,2096,12,education,good
3,3,45,male,2,free,little,little,7882,42,furniture/equipment,good
4,4,53,male,2,free,little,little,4870,24,car,bad

Para construir la tabla de contingencia utilizamos el comando crosstab() de pandas.

In [76]:
tabla = pd.crosstab(index = banco['Sex'], columns= banco['Risk'], normalize = 'index')
tabla

Risk         bad      good
Sex
female  0.351613  0.648387
male    0.276812  0.723188

Utilizamos el comando iloc[] para recorrer las filas y columnas de un DataFrame.

### **Ejercicio**

Construir la tabla de contingencia de las variables categóricas de las siguientes bases de datos

In [10]:
ciclop = pd.read_csv('local/data/cicloparqueaderos-del-sistema-transmilenio-febrero-2022.csv', index_col=0, encoding='latin-1', sep = ';')
print(ciclop.shape)
ciclop.head()

(20, 6)

,Tipo de infraestructura,Troncal de TransMilenio,Promedio Hábil,Promedio Sábado,Promedio Domingos y festivos,Cupos
Cicloparqueadero,,,,,,
San Mateo,Estación,NQS Sur,1.139,786.0,351.0,1.449
Portal Américas,Portal,Américas,645.000,354.0,167.0,785.000
Portal Sur,Portal,NQS Sur,343.000,239.0,109.0,409.000
Portal Suba,Portal,Suba,489.000,331.0,137.0,710.000
Portal Eldorado,Portal,Calle 26,333.000,197.0,59.0,532.000

In [17]:
buses = pd.read_csv('local/data/buses-en-operacion-marzo-2022.csv', index_col=0, encoding='latin-1', sep = ';')
print(buses.shape)
buses.head()

(10342, 12)

,Etiqueta,Matricula,TipoVehiculo,TipoServicio,Sintetizador SIRCI,NivelEmision,Marca,Accesible,Operador,Modelo,Zona,Concesion
Vehiculo,,,,,,,,,,,,
6001,B0001,SIS805,ARTICULADO,TRONCAL,SI,EURO II,VOLVO,PLATAFORMA ALTA,CONNEXIÓN MOVIL,2004,SUR,AUTOPISTA SUR T2
6002,B0002,SIS806,ARTICULADO,TRONCAL,SI,EURO II,VOLVO,PLATAFORMA ALTA,CONNEXIÓN MOVIL,2004,SUR,AUTOPISTA SUR T2
6003,B0003,SIS807,ARTICULADO,TRONCAL,SI,EURO II,VOLVO,PLATAFORMA ALTA,CONNEXIÓN MOVIL,2004,SUR,AUTOPISTA SUR T2
6004,B0004,SIS808,ARTICULADO,TRONCAL,SI,EURO II,VOLVO,PLATAFORMA ALTA,CONNEXIÓN MOVIL,2004,SUR,AUTOPISTA SUR T2
6005,B0005,SIS809,ARTICULADO,TRONCAL,SI,EURO II,VOLVO,PLATAFORMA ALTA,CONNEXIÓN MOVIL,2004,SUR,AUTOPISTA SUR T2

### **Tabla de frecuencias relativas**

En una tabla de frecuencias relativas, cada celda representa la proporción de elementos que pertenecen a la fila y columna en la que está. La frecuencia relativa de la fila $i$ y la columna $j$ se denota por $h_{ij}$ y se calcula de la siguiente manera:

$$
    h_{ij} = \dfrac{f_{ij}}{n}.
$$

### **Propiedad**

La suma de todas las frecuencias relativas es igual a 1

$$
      \sum_{i=1}^c\sum_{j=1}^rh_{ij} = 1.
$$

A partir de la definición de tabla de contingencia relativa, podemos concluir que 
$$
    h_{ij} = P(A_i\cap B_j),
$$

donde $A_i$ es la característica de la $i$-ésima fila, $B_j$ es la caracterísitca de la columna $j$-ésima y $P(A_i\cap B_j)$ es la probabilidad de la intersección de los dos eventos.

In [81]:
tabla_n = pd.crosstab(index = banco['Sex'], columns= banco['Risk'], normalize = True)
tabla_n

Risk      bad   good
Sex
female  0.109  0.201
male    0.191  0.499

Calculemos la probabilidad de que la persona sea mujer y que su calificación de riesgo sea buena.

Podemos normalizar la tabla de contingencia por el índice (filas) o por columnas.

### **Frecuencias Marginales**

En una tabla de frecuencias, llamamos frecuencias a la suma de las frecuencias de cada fila o columna.

La frecuencia marginal de la fila $i$ se denota por $f_{i\bullet}$
La frecuencia marginal de la columna $j$ se denota por $f_{\bullet j}$
Para calcular la frecuencia marginal de la fila $i$, sumamos en esa fila todas las columnas

$$
f_{i\bullet}=\sum_{j=1}^r f_{ij}
$$

Para calcular la frecuencia marginal de la columna j, sumamos en esa columna todas las filas

$$
f_{\bullet j}=\sum_{i=1}^c f_{ij}
$$

In [80]:
tabla_m = pd.crosstab(banco['Sex'], banco['Risk'], margins = True)
tabla_m

Risk    bad  good   All
Sex
female  109   201   310
male    191   499   690
All     300   700  1000

### **Frecuencias relativas marginales**

También podemos calcular Frecuencias relativas marginales, dividiendo las frecuencias marginales entre el tamaño de la muestra o sumando las frecuencias relativas por filas o columnas:
$$
h_{i\bullet} = \dfrac{f_{i\bullet}}{n}=\sum_{j=1}^r h_{ij}\qquad h_{\bullet j} = \dfrac{f_{\bullet j}}{n}=\sum_{i=1}^c h_{ij}
$$

1. Calculemos la probabilidad de que un cliente del banco sea hombre.
2. Calculemos la probabilidad de que un cliente del banco tenga una calificación de riesgo mala.

### **Frecuencias condicionales**

Si nos interesa saber qué proporción de una fila o una columna representa una frecuencia conjunta, debemos calcular una Frecuencia condicional.

* La frecuencia condicional de la fila $i$ dada la columna $j$ se denota por $f_{i|c=j}$.
$$
f_{i|c=j} = \dfrac{f_{ij}}{f_{\bullet j}} = \dfrac{h_{ij}}{h_{\bullet j}}
$$
* La frecuencia condicional de la columna j dada la fila i se denota por $f_{j|r=i}$
$$
f_{j|r=i} = \dfrac{f_{ij}}{f_{i\bullet}} = \dfrac{h_{ij}}{h_{i\bullet }}.
$$

A partir de la probabilidad (frecuencia relativa) de la intersección de los dos eventos $A_i$ y $B_j$ y la frecuencia marginal relativa, tenemos que

$$
P(A_i|B_j) = \dfrac{P(A_i\cap B_j)}{P(B_{\bullet j})}\qquad\text{y}\qquad P(B_j|A_i) = \dfrac{P(A_i\cap B_j)}{P(A_{i\bullet})}
$$

1. Calcular la probabilidad de que un cliente sea hombre dado que tiene una calificación de riesgo mala.
2. Calcular la probabilidad de que un cliente tenga una calificación de riesgo mala dado que el cliente es un hombre.